//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uncreated.Framework.UI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Uncreated.Framework.UI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Labeled Button.
        /// </summary>
        internal static string DisplayName_LabeledButton {
            get {
                return ResourceManager.GetString("DisplayName_LabeledButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Labeled Right-Clickable Button.
        /// </summary>
        internal static string DisplayName_LabeledRightClickableButton {
            get {
                return ResourceManager.GetString("DisplayName_LabeledRightClickableButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Labeled Right-Clickable State Button.
        /// </summary>
        internal static string DisplayName_LabeledRightClickableStateButton {
            get {
                return ResourceManager.GetString("DisplayName_LabeledRightClickableStateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Labeled State Button.
        /// </summary>
        internal static string DisplayName_LabeledStateButton {
            get {
                return ResourceManager.GetString("DisplayName_LabeledStateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Labeled Toggle.
        /// </summary>
        internal static string DisplayName_LabeledUnturnedToggle {
            get {
                return ResourceManager.GetString("DisplayName_LabeledUnturnedToggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;uninitialized&gt;.
        /// </summary>
        internal static string DisplayName_PatternRoot_Uninitialized {
            get {
                return ResourceManager.GetString("DisplayName_PatternRoot_Uninitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placeholder Text Box.
        /// </summary>
        internal static string DisplayName_PlaceholderTextBox {
            get {
                return ResourceManager.GetString("DisplayName_PlaceholderTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right-Clickable Button.
        /// </summary>
        internal static string DisplayName_RightClickableButton {
            get {
                return ResourceManager.GetString("DisplayName_RightClickableButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right-Clickable State Button.
        /// </summary>
        internal static string DisplayName_RightClickableStateButton {
            get {
                return ResourceManager.GetString("DisplayName_RightClickableStateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State Button.
        /// </summary>
        internal static string DisplayName_StateButton {
            get {
                return ResourceManager.GetString("DisplayName_StateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State Placeholder Text Box.
        /// </summary>
        internal static string DisplayName_StatePlaceholderTextBox {
            get {
                return ResourceManager.GetString("DisplayName_StatePlaceholderTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State Text Box.
        /// </summary>
        internal static string DisplayName_StateTextBox {
            get {
                return ResourceManager.GetString("DisplayName_StateTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button.
        /// </summary>
        internal static string DisplayName_UnturnedButton {
            get {
                return ResourceManager.GetString("DisplayName_UnturnedButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Enum Button.
        /// </summary>
        internal static string DisplayName_UnturnedEnumButton {
            get {
                return ResourceManager.GetString("DisplayName_UnturnedEnumButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        internal static string DisplayName_UnturnedImage {
            get {
                return ResourceManager.GetString("DisplayName_UnturnedImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label.
        /// </summary>
        internal static string DisplayName_UnturnedLabel {
            get {
                return ResourceManager.GetString("DisplayName_UnturnedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Box.
        /// </summary>
        internal static string DisplayName_UnturnedTextBox {
            get {
                return ResourceManager.GetString("DisplayName_UnturnedTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle.
        /// </summary>
        internal static string DisplayName_UnturnedToggle {
            get {
                return ResourceManager.GetString("DisplayName_UnturnedToggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UI Element.
        /// </summary>
        internal static string DisplayName_UnturnedUIElement {
            get {
                return ResourceManager.GetString("DisplayName_UnturnedUIElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pattern class {0} defines enumerable property {1} without decorating it with an ArrayPatternAttribute..
        /// </summary>
        internal static string Exception_ArrayAttributeNotSpecified {
            get {
                return ResourceManager.GetString("Exception_ArrayAttributeNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pattern class {0} decorates {1} with an ArrayPatternAttribute when it isn&apos;t an enumerable..
        /// </summary>
        internal static string Exception_ArrayAttributeSpecifiedOnSingular {
            get {
                return ResourceManager.GetString("Exception_ArrayAttributeSpecifiedOnSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pattern class {0} defines an array as a root object. Arrays can not be root objects..
        /// </summary>
        internal static string Exception_ArrayRootObject {
            get {
                return ResourceManager.GetString("Exception_ArrayRootObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type {0} caused a circular reference terminated by pattern variable {1}..
        /// </summary>
        internal static string Exception_CircularReference {
            get {
                return ResourceManager.GetString("Exception_CircularReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected constructor on preset type {0} threw an exception, or was unable to create the preset for some reason..
        /// </summary>
        internal static string Exception_ErrorRunningPresetConstructor {
            get {
                return ResourceManager.GetString("Exception_ErrorRunningPresetConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The constructor on primitive type {0} threw an exception, or was unable to create the primitive for some reason..
        /// </summary>
        internal static string Exception_ErrorRunningPrimitiveConstructor {
            get {
                return ResourceManager.GetString("Exception_ErrorRunningPrimitiveConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setter for {0} threw an exception on {1} while creating pattern..
        /// </summary>
        internal static string Exception_ErrorSettingTextBoxUseData {
            get {
                return ResourceManager.GetString("Exception_ErrorSettingTextBoxUseData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The setter for variable {0} threw an exception on type {1}, or there was some other issue setting the variable while creating pattern..
        /// </summary>
        internal static string Exception_ErrorSettingVariable {
            get {
                return ResourceManager.GetString("Exception_ErrorSettingVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create instance of pattern class {0}. All patterns must have a parameterless constructor (created by default if no other constructors are available)..
        /// </summary>
        internal static string Exception_FailedToCreatePatternClass {
            get {
                return ResourceManager.GetString("Exception_FailedToCreatePatternClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to initialize type {0} when creating {1}..
        /// </summary>
        internal static string Exception_FailureCreatingPrimitive {
            get {
                return ResourceManager.GetString("Exception_FailureCreatingPrimitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Array in pattern class {0} at property {1} is too small for the amount of elements required..
        /// </summary>
        internal static string Exception_FillEnumerableArrayTooSmall {
            get {
                return ResourceManager.GetString("Exception_FillEnumerableArrayTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pattern class {0} has a non-null value for {1} which is an enumerable type that isn&apos;t assignable to the ICollection&lt;&gt; type for it&apos;s expected element. Values can not be added to this enumerable..
        /// </summary>
        internal static string Exception_FillEnumerableNotValidType {
            get {
                return ResourceManager.GetString("Exception_FillEnumerableNotValidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inconsistent values in arguments: &apos;to&apos;, and &apos;length&apos;..
        /// </summary>
        internal static string Exception_InconsistantLengthArguments {
            get {
                return ResourceManager.GetString("Exception_InconsistantLengthArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created data does not store the same player and element as expected..
        /// </summary>
        internal static string Exception_InconsistantPlayerFromCreatedDataElement {
            get {
                return ResourceManager.GetString("Exception_InconsistantPlayerFromCreatedDataElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created data does not store the same player and UI as expected..
        /// </summary>
        internal static string Exception_InconsistantPlayerFromCreatedDataUI {
            get {
                return ResourceManager.GetString("Exception_InconsistantPlayerFromCreatedDataUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to register an UnturnedUI object as an element..
        /// </summary>
        internal static string Exception_LateRegisterUnturnedUI {
            get {
                return ResourceManager.GetString("Exception_LateRegisterUnturnedUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must either specify &apos;to&apos; or &apos;length&apos;..
        /// </summary>
        internal static string Exception_MissingLengthArguments {
            get {
                return ResourceManager.GetString("Exception_MissingLengthArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pattern class {0} has more than one root element defined. There can not be more than one root element..
        /// </summary>
        internal static string Exception_MultipleRootObjects {
            get {
                return ResourceManager.GetString("Exception_MultipleRootObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigational path segments like &apos;.&apos; and &apos;..&apos; are not supported in the &apos;relative to&apos; path..
        /// </summary>
        internal static string Exception_NavigationPathsNotSupportedInRelevantPath {
            get {
                return ResourceManager.GetString("Exception_NavigationPathsNotSupportedInRelevantPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pattern class {0} defines a multi-dimensional or non-zero based array. Non-SZ arrays are not supportted..
        /// </summary>
        internal static string Exception_NonSZArray {
            get {
                return ResourceManager.GetString("Exception_NonSZArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This function should only be called from the game thread. (e.g. from Unity&apos;s Update).
        /// </summary>
        internal static string Exception_NotOnValidThread {
            get {
                return ResourceManager.GetString("Exception_NotOnValidThread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The relative path navigates further up than the root object..
        /// </summary>
        internal static string Exception_RelativePathExceedsRoot {
            get {
                return ResourceManager.GetString("Exception_RelativePathExceedsRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This element&apos;s owner UI has a key of -1. A -1 key is usually only used to make Unturned respect the effect&apos;s lifetime..
        /// </summary>
        internal static string Exception_UIOwnerM1Key {
            get {
                return ResourceManager.GetString("Exception_UIOwnerM1Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This element does not have an owner UI. Make sure the element was initialized as a field or property in it&apos;s owner&apos;s class..
        /// </summary>
        internal static string Exception_UIOwnerNotSet {
            get {
                return ResourceManager.GetString("Exception_UIOwnerNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pattern class {0} defines an invalid enumerable type on property {1} which can not be auto-generated..
        /// </summary>
        internal static string Exception_UnknownEnumerableType {
            get {
                return ResourceManager.GetString("Exception_UnknownEnumerableType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnturnedUI data methods can only be used on data linked to this UI and no element..
        /// </summary>
        internal static string Exception_UnrelatedUIDataType {
            get {
                return ResourceManager.GetString("Exception_UnrelatedUIDataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] Cleared from all players..
        /// </summary>
        internal static string Log_ClearFromAllPlayers {
            get {
                return ResourceManager.GetString("Log_ClearFromAllPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] Cleared from {1}..
        /// </summary>
        internal static string Log_ClearFromPlayer {
            get {
                return ResourceManager.GetString("Log_ClearFromPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] Deregistering {1} elements..
        /// </summary>
        internal static string Log_DeregisteringPrimitives {
            get {
                return ResourceManager.GetString("Log_DeregisteringPrimitives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] [{1}] {{{2}}} There is already a button with name \&quot;{3}\&quot;, replacing. Multiple buttons can not listen to events with the same name. Old button: \&quot;{4}\&quot;. This button: \&quot;{5}\&quot;..
        /// </summary>
        internal static string Log_DuplicateButtonName {
            get {
                return ResourceManager.GetString("Log_DuplicateButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] [{1}] {{{2}}} There is already a text box with name \&quot;{3}\&quot;, replacing. Multiple text boxes can not listen to events with the same name. Old text box: \&quot;{4}\&quot;. This text box: \&quot;{5}\&quot;..
        /// </summary>
        internal static string Log_DuplicateTextBoxName {
            get {
                return ResourceManager.GetString("Log_DuplicateTextBoxName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error invoking main thread dispatch..
        /// </summary>
        internal static string Log_ErrorDispatchingMainThreadEvent {
            get {
                return ResourceManager.GetString("Log_ErrorDispatchingMainThreadEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error invoking main thread dispatch (without dispatching)..
        /// </summary>
        internal static string Log_ErrorDispatchingMainThreadEvent_NoContextSwitch {
            get {
                return ResourceManager.GetString("Log_ErrorDispatchingMainThreadEvent_NoContextSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to dispose UI provider: {0}..
        /// </summary>
        internal static string Log_ErrorDisposingIUnturnedUIProvider {
            get {
                return ResourceManager.GetString("Log_ErrorDisposingIUnturnedUIProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} threw an exception from an override of the OnDisposing method..
        /// </summary>
        internal static string Log_ErrorDisposingUnturnedUI {
            get {
                return ResourceManager.GetString("Log_ErrorDisposingUnturnedUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] [{1}] Error invoking {2}..
        /// </summary>
        internal static string Log_EventError {
            get {
                return ResourceManager.GetString("Log_EventError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] Found IUnturnedUIElementProvider containing {1} element(s)..
        /// </summary>
        internal static string Log_FoundIUnturnedUIElementProvider {
            get {
                return ResourceManager.GetString("Log_FoundIUnturnedUIElementProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] Found object containing the previous {1} element(s): {2}..
        /// </summary>
        internal static string Log_FoundOther {
            get {
                return ResourceManager.GetString("Log_FoundOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] Found object (enumerable member) containing the previous {1} element(s): {2}..
        /// </summary>
        internal static string Log_FoundOtherInEnumerable {
            get {
                return ResourceManager.GetString("Log_FoundOtherInEnumerable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] Found element: {1}..
        /// </summary>
        internal static string Log_FoundPrimitive {
            get {
                return ResourceManager.GetString("Log_FoundPrimitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] Found element (enumerable member): {1}..
        /// </summary>
        internal static string Log_FoundPrimitiveInEnumerable {
            get {
                return ResourceManager.GetString("Log_FoundPrimitiveInEnumerable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] Found element (IUnturnedUIElementProvider): {1}..
        /// </summary>
        internal static string Log_FoundPrimitiveInIUnturnedUIElementProvider {
            get {
                return ResourceManager.GetString("Log_FoundPrimitiveInIUnturnedUIElementProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] Late-registered object containing the previous {1} element(s): {2}..
        /// </summary>
        internal static string Log_LateRegisteredOther {
            get {
                return ResourceManager.GetString("Log_LateRegisteredOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] Late-registered element: {1}..
        /// </summary>
        internal static string Log_LateRegisteredPrimitive {
            get {
                return ResourceManager.GetString("Log_LateRegisteredPrimitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] Unable to find an Asset, ID, or GUID..
        /// </summary>
        internal static string Log_NoAssetSupplied {
            get {
                return ResourceManager.GetString("Log_NoAssetSupplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] Sent to all players..
        /// </summary>
        internal static string Log_SendToAllPlayers_0 {
            get {
                return ResourceManager.GetString("Log_SendToAllPlayers_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] Sent to all players, args: {{0}} = {1}..
        /// </summary>
        internal static string Log_SendToAllPlayers_1 {
            get {
                return ResourceManager.GetString("Log_SendToAllPlayers_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] Sent to all players, args: {{0}} = {1}, {{1}} = {2}..
        /// </summary>
        internal static string Log_SendToAllPlayers_2 {
            get {
                return ResourceManager.GetString("Log_SendToAllPlayers_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] Sent to all players, args: {{0}} = {1}, {{1}} = {2}, {{2}} = {3}..
        /// </summary>
        internal static string Log_SendToAllPlayers_3 {
            get {
                return ResourceManager.GetString("Log_SendToAllPlayers_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] Sent to all players, args: {{0}} = {1}, {{1}} = {2}, {{2}} = {3}, {{3}} = {4}..
        /// </summary>
        internal static string Log_SendToAllPlayers_4 {
            get {
                return ResourceManager.GetString("Log_SendToAllPlayers_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] Sent to {1}..
        /// </summary>
        internal static string Log_SendToPlayer_0 {
            get {
                return ResourceManager.GetString("Log_SendToPlayer_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] Sent to {1}, args: {{0}} = {2}..
        /// </summary>
        internal static string Log_SendToPlayer_1 {
            get {
                return ResourceManager.GetString("Log_SendToPlayer_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] Sent to {1}, args: {{0}} = {2}, {{1}} = {3}..
        /// </summary>
        internal static string Log_SendToPlayer_2 {
            get {
                return ResourceManager.GetString("Log_SendToPlayer_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] Sent to {1}, args: {{0}} = {2}, {{1}} = {3}, {{2}} = {4}..
        /// </summary>
        internal static string Log_SendToPlayer_3 {
            get {
                return ResourceManager.GetString("Log_SendToPlayer_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] Sent to {1}, args: {{0}} = {2}, {{1}} = {3}, {{2}} = {4}, {{3}} = {5}..
        /// </summary>
        internal static string Log_SendToPlayer_4 {
            get {
                return ResourceManager.GetString("Log_SendToPlayer_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] Unable to find an effect asset with GUID {1}..
        /// </summary>
        internal static string Log_UnableToFindAssetFromGuid {
            get {
                return ResourceManager.GetString("Log_UnableToFindAssetFromGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] Unable to find an effect asset with ID {1}..
        /// </summary>
        internal static string Log_UnableToFindAssetFromId {
            get {
                return ResourceManager.GetString("Log_UnableToFindAssetFromId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] Effect asset {1} does not have a valid numeric ID..
        /// </summary>
        internal static string Log_UnableToFindIdFromAsset {
            get {
                return ResourceManager.GetString("Log_UnableToFindIdFromAsset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] [{1}] {{{2}}} Clicked by {3}..
        /// </summary>
        internal static string Log_UnturnedButtonClicked {
            get {
                return ResourceManager.GetString("Log_UnturnedButtonClicked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] [{1}] {{{2}}} Set image URL, link: {3}, force refresh: {4}..
        /// </summary>
        internal static string Log_UnturnedImageUpdated {
            get {
                return ResourceManager.GetString("Log_UnturnedImageUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] [{1}] {{{2}}} Set label text: \&quot;{3}\&quot;..
        /// </summary>
        internal static string Log_UnturnedLabelUpdated {
            get {
                return ResourceManager.GetString("Log_UnturnedLabelUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] [{1}] {{{2}}} Text committed by {3}, text: \&quot;{4}\&quot;..
        /// </summary>
        internal static string Log_UnturnedTextBoxCommitted {
            get {
                return ResourceManager.GetString("Log_UnturnedTextBoxCommitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] [{1}] {{{2}}} Text updated from data for {3}, text: \&quot;{4}\&quot; (event not invoked)..
        /// </summary>
        internal static string Log_UnturnedTextBoxUpdatedFromData {
            get {
                return ResourceManager.GetString("Log_UnturnedTextBoxUpdatedFromData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] [{1}] {{{2}}} Set visibility for {3}, visibility: {4}..
        /// </summary>
        internal static string Log_UnturnedUIElementVisibilityUpdated {
            get {
                return ResourceManager.GetString("Log_UnturnedUIElementVisibilityUpdated", resourceCulture);
            }
        }
    }
}
