name: Latest

on:
  pull_request:
    types: [ opened, reopened ]
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: 'master'
        
    - name: SetupDotNet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.x.x'
        
    - name: Build
      run: dotnet build "./UncreatedUI/Uncreated.UI.csproj" --configuration Release "/p:IsInGitHubActions=True"
        
    - name: Test
      run: dotnet test "./Uncreated.UI.Tests/Uncreated.UI.Tests.csproj" --configuration Release "/p:IsInGitHubActions=True"